micronaut:
  application:
    name: fourmonth
netty:
  default:
    allocator:
      max-order: 3
vertx:
  pg:
    client:
      port: 5432
      host: localhost
      database: postgres
      user: postgres
      password: mysecretpassword
      maxSize: 5
